name:  MO Checkin Regression On TKE

on:
  pull_request_target:
    branches: [ main,'[0-9]+.[0-9]+*',cn-bvt-1 ]
    types:
      - closed
    paths:
      - '**.go'
      - '**.c'
      - '**.h'
      - 'test/distributed/**'

jobs:
  mo-checkin-regression:
    name: MO Checkin Regression On TKE
    uses: Rosyrain/CI/.github/workflows/merge-trigger-tke.yaml@CI-mo-cn-bvt
    secrets: inherit
