name: WeWork Robot

# Controls when the workflow will run
on:
  issues:
    types: [closed, assigned, opened]
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  wework-robot:
    name: WeWork Robot
    uses: Rosyrain/CI/.github/workflows/robot.yaml@CI-mo-cn-bvt
    secrets: inherit
